[package]
name = "payground-open"
version = "0.1.0"
edition = "2021"

[dependencies]

lib-calculator = { path = "../lib-calculator" }

thiserror = "2.0.11"
cubecl-core = { workspace = true }
cubecl-cuda = { workspace = true }


[profile.release]
opt-level = 3
lto = true
codegen-units = 1
